"""Second-axis hash service tests (Phase 3.2.1).

Pins acceptance #3-#5 of task 3.2.1 + the load-bearing invariant from
vision.md:1019:

- #3 — ``compute_source_hash_for`` deterministic; ``parent.enclosing_context``
  change flips the key; stability preserves it.
- #4 — axis independence: a change to the **node's own** ``content_hash``
  (or any other own content field) with stable ``parent.enclosing_context``
  must NOT change ``enclosing_context_source_hash``.
- #5 — short-circuit: ``is_stale`` returns ``False`` when stored equals
  computed, ``True`` otherwise; ``None == None`` is the legitimate
  "stable-absence" case (root or non-root child whose parent has no
  enclosing_context yet).
- Bearing invariant (vision.md:1019) — stable ``parent.enclosing_context``
  ⇒ byte-stable ``source_hash`` regardless of how many times we recompute.

Mirror-sibling shape of ``test_node_summary_formulas.py`` (Phase 3.1):
AsyncMock session, ``_make_raw`` builder with sane defaults, focused
per-property classes. ``_StubService`` overrides ``_fetch_parent_raw``
to bypass the DB lookup — the lookup itself is covered separately so
the formula / staleness tests do not couple to query mocking shape.
"""

from __future__ import annotations

import uuid
from typing import Any
from unittest.mock import AsyncMock

import pytest

from course_supporter.storage.enclosing_context_hash import (
    EnclosingContextHashService,
)
from course_supporter.storage.orm import NodeSummaryRaw


def _make_raw(**overrides: Any) -> NodeSummaryRaw:
    """Build a NodeSummaryRaw with sane defaults; override individual fields.

    Mirrors ``_make_raw`` in ``test_node_summary_formulas.py`` for
    consistency across the storage test suite.
    """
    defaults: dict[str, Any] = {
        "id": uuid.uuid4(),
        "course_node_id": uuid.uuid4(),
        "title": "Node Title",
        "description": "Node description",
        "learning_objectives": [],
        "knowledge": [],
        "skills": [],
        "success_criteria": [],
        "assessment_approach": "",
        "teaching_approach": "",
        "key_activities": [],
        "common_mistakes": [],
        "main_concepts": [],
        "secondary_concepts": [],
        "compressed_summary": "",
        "enclosing_context": None,
        "methodist_observations": [],
        "own_documents_count": 0,
        "own_chars_count": 0,
        "cumulative_documents_count": 0,
        "cumulative_chars_count": 0,
        "enclosing_context_source_hash": None,
    }
    defaults.update(overrides)
    raw = NodeSummaryRaw(**defaults)
    raw.deleted_at = None
    return raw


class _StubService(EnclosingContextHashService):
    """``EnclosingContextHashService`` with the DB-side parent resolver
    stubbed out.

    Allows formula / staleness tests to control the resolved parent
    directly. The real ``_fetch_parent_raw`` is covered by its own
    test class.
    """

    def __init__(self, parent_raw: NodeSummaryRaw | None) -> None:
        super().__init__(session=AsyncMock())
        self._stub_parent = parent_raw

    async def _fetch_parent_raw(self, node: Any) -> NodeSummaryRaw | None:
        return self._stub_parent


# ── compute_source_hash_for ──────────────────────────────────────


class TestComputeSourceHashForFormula:
    """``compute_source_hash_for`` derives the key from ``parent.enclosing_context``
    via the same pure helpers as the first-axis formulas. Acceptance #3.
    """

    async def test_deterministic_across_calls(self) -> None:
        parent = _make_raw(enclosing_context="course-level methodist context")
        child = _make_raw(course_node_id=uuid.uuid4())
        svc = _StubService(parent_raw=parent)
        first = await svc.compute_source_hash_for(child)
        second = await svc.compute_source_hash_for(child)
        assert first == second

    async def test_parent_context_change_flips_hash(self) -> None:
        # Acceptance #3 load-bearing assertion.
        a_parent = _make_raw(enclosing_context="version one")
        b_parent = _make_raw(enclosing_context="version two")
        child = _make_raw()
        a_hash = await _StubService(parent_raw=a_parent).compute_source_hash_for(child)
        b_hash = await _StubService(parent_raw=b_parent).compute_source_hash_for(child)
        assert a_hash != b_hash

    async def test_parent_context_none_and_empty_string_equivalent(self) -> None:
        # ``None``-coalesce to ``""`` mirrors the convention in
        # ``_node_summary_raw_payload`` — absent enclosing_context (parent
        # not yet generated by 3.2.3) hashes the same as explicit empty
        # string, so children get a deterministic "context-absent" key.
        none_parent = _make_raw(enclosing_context=None)
        empty_parent = _make_raw(enclosing_context="")
        child = _make_raw()
        none_hash = await _StubService(parent_raw=none_parent).compute_source_hash_for(
            child
        )
        empty_hash = await _StubService(
            parent_raw=empty_parent
        ).compute_source_hash_for(child)
        assert none_hash == empty_hash
        assert none_hash is not None  # absent → "" still yields a real hash

    async def test_hash_is_64_char_hex(self) -> None:
        parent = _make_raw(enclosing_context="something")
        child = _make_raw()
        digest = await _StubService(parent_raw=parent).compute_source_hash_for(child)
        assert digest is not None
        assert len(digest) == 64
        assert all(c in "0123456789abcdef" for c in digest)


class TestRootSemantics:
    """Root CourseNode → ``compute_source_hash_for`` returns ``None``
    (Q-B Option 1 — key undefined by construction). Acceptance #3 + Q-B.
    """

    async def test_root_returns_none(self) -> None:
        child = _make_raw()
        svc = _StubService(parent_raw=None)
        assert await svc.compute_source_hash_for(child) is None

    async def test_root_independent_of_own_enclosing_context(self) -> None:
        # Even if the root's own ``enclosing_context`` were somehow set
        # (it shouldn't be — vision §262 says NULL on root — but the
        # service must not read self for the second axis), the key is
        # still None because there's no parent.
        child = _make_raw(enclosing_context="unexpected value on a root")
        svc = _StubService(parent_raw=None)
        assert await svc.compute_source_hash_for(child) is None


# ── Axis independence (acceptance #4) ────────────────────────────


class TestAxisIndependence:
    """The second axis depends ONLY on ``parent.enclosing_context`` —
    never on the node's own ``content_hash`` or own content fields.
    Acceptance #4 — the structural separation between bottom-up (first
    axis) and top-down (second axis).
    """

    async def test_own_content_hash_change_does_not_flip_source_hash(
        self,
    ) -> None:
        parent = _make_raw(enclosing_context="stable parent context")
        # Same parent (== same source_hash input); two children whose
        # only difference is their own content_hash. The second-axis
        # key MUST be identical — the first axis owns content changes.
        child_a = _make_raw()
        child_a.content_hash = "a" * 64
        child_b = _make_raw()
        child_b.content_hash = "b" * 64
        svc = _StubService(parent_raw=parent)
        a_hash = await svc.compute_source_hash_for(child_a)
        b_hash = await svc.compute_source_hash_for(child_b)
        assert a_hash == b_hash

    async def test_own_content_field_change_does_not_flip_source_hash(
        self,
    ) -> None:
        parent = _make_raw(enclosing_context="stable parent context")
        # Same parent; children whose own content fields differ (title,
        # main_concepts, etc.) — first-axis hash would diverge, second
        # axis must NOT.
        child_a = _make_raw(title="Lesson one", main_concepts=["loops"])
        child_b = _make_raw(title="Lesson two", main_concepts=["recursion"])
        svc = _StubService(parent_raw=parent)
        a_hash = await svc.compute_source_hash_for(child_a)
        b_hash = await svc.compute_source_hash_for(child_b)
        assert a_hash == b_hash


# ── is_stale (acceptance #5) ─────────────────────────────────────


class TestIsStale:
    """``is_stale`` is the per-node short-circuit primitive. Acceptance #5."""

    async def test_match_returns_false(self) -> None:
        parent = _make_raw(enclosing_context="parent context")
        child = _make_raw()
        svc = _StubService(parent_raw=parent)
        # Pre-populate child's stored hash with the value that would be
        # computed right now — i.e. an already-up-to-date node.
        child.enclosing_context_source_hash = await svc.compute_source_hash_for(child)
        assert await svc.is_stale(child) is False

    async def test_mismatch_returns_true(self) -> None:
        parent = _make_raw(enclosing_context="parent context")
        child = _make_raw(enclosing_context_source_hash="some-old-stored-hash")
        svc = _StubService(parent_raw=parent)
        assert await svc.is_stale(child) is True

    async def test_root_stable_absence_is_not_stale(self) -> None:
        # Stable-absence case: root (parent_raw=None) + stored is None
        # → not stale. The orchestrator should NOT keep retrying root.
        child = _make_raw(enclosing_context_source_hash=None)
        svc = _StubService(parent_raw=None)
        assert await svc.is_stale(child) is False

    async def test_root_with_lingering_stored_hash_is_stale(self) -> None:
        # If a root somehow has a stored source_hash (e.g. node was
        # demoted from non-root to root) — staleness reports True so
        # the orchestrator can clear it.
        child = _make_raw(enclosing_context_source_hash="stale-from-prior-life")
        svc = _StubService(parent_raw=None)
        assert await svc.is_stale(child) is True


# ── update_source_hash ───────────────────────────────────────────


class TestUpdateSourceHash:
    """``update_source_hash`` sets the attribute and flushes."""

    async def test_writes_value_and_flushes(self) -> None:
        child = _make_raw(enclosing_context_source_hash=None)
        session = AsyncMock()
        svc = EnclosingContextHashService(session=session)
        await svc.update_source_hash(child, "fresh-hash-value")
        assert child.enclosing_context_source_hash == "fresh-hash-value"
        session.flush.assert_awaited_once()

    async def test_can_clear_to_none(self) -> None:
        child = _make_raw(enclosing_context_source_hash="prior-value")
        session = AsyncMock()
        svc = EnclosingContextHashService(session=session)
        await svc.update_source_hash(child, None)
        assert child.enclosing_context_source_hash is None
        session.flush.assert_awaited_once()


# ── Parent resolution (two-hop CourseNode lookup) ────────────────


class TestFetchParentRaw:
    """``_fetch_parent_raw`` walks CourseNode → parent_id → parent Raw.

    Drives the real resolver against an ``AsyncMock`` session that
    returns a synthetic ``CourseNode`` (for ``session.get``) and a
    synthetic parent Raw (for the ``select`` query result).
    """

    async def test_root_returns_none(self) -> None:
        # CourseNode with parent_id IS NULL → no parent Raw.
        from course_supporter.storage.orm import CourseNode

        course_node = CourseNode(
            id=uuid.uuid4(),
            tenant_id=uuid.uuid4(),
            parent_id=None,
            title="root",
            default_language="ukr",
        )
        session = AsyncMock()
        session.get.return_value = course_node
        svc = EnclosingContextHashService(session=session)
        child = _make_raw(course_node_id=course_node.id)
        result = await svc._fetch_parent_raw(child)
        assert result is None
        # No SELECT issued — short-circuited at parent_id IS NULL.
        session.execute.assert_not_called()

    async def test_non_root_returns_parent_raw(self) -> None:
        from unittest.mock import MagicMock

        from course_supporter.storage.orm import CourseNode

        parent_node_id = uuid.uuid4()
        course_node = CourseNode(
            id=uuid.uuid4(),
            tenant_id=uuid.uuid4(),
            parent_id=parent_node_id,
            title="child node",
        )
        parent_raw = _make_raw(
            course_node_id=parent_node_id,
            enclosing_context="parent ctx",
        )
        session = AsyncMock()
        session.get.return_value = course_node
        # ``select(...).scalar_one_or_none()`` returns the parent Raw.
        result_mock = MagicMock()
        result_mock.scalar_one_or_none.return_value = parent_raw
        session.execute.return_value = result_mock
        svc = EnclosingContextHashService(session=session)
        child = _make_raw(course_node_id=course_node.id)
        result = await svc._fetch_parent_raw(child)
        assert result is parent_raw

    async def test_missing_course_node_returns_none(self) -> None:
        # Invariant-violation: CourseNode for the node does not exist
        # (orchestrator out-of-order'd or data drift). Service returns
        # None rather than raising — downstream policy decides.
        session = AsyncMock()
        session.get.return_value = None
        svc = EnclosingContextHashService(session=session)
        child = _make_raw()
        result = await svc._fetch_parent_raw(child)
        assert result is None

    async def test_parent_course_node_exists_but_parent_raw_missing(
        self,
    ) -> None:
        # Edge case: parent CourseNode exists but its NodeSummaryRaw
        # hasn't been generated yet (orchestrator out-of-order'd —
        # walked children before parent). Returns None rather than
        # raising; orchestrator-side policy.
        from unittest.mock import MagicMock

        from course_supporter.storage.orm import CourseNode

        course_node = CourseNode(
            id=uuid.uuid4(),
            tenant_id=uuid.uuid4(),
            parent_id=uuid.uuid4(),
            title="child node",
        )
        session = AsyncMock()
        session.get.return_value = course_node
        result_mock = MagicMock()
        result_mock.scalar_one_or_none.return_value = None
        session.execute.return_value = result_mock
        svc = EnclosingContextHashService(session=session)
        child = _make_raw(course_node_id=course_node.id)
        result = await svc._fetch_parent_raw(child)
        assert result is None


# ── Bearing invariant (vision.md:1019) ───────────────────────────


class TestBearingInvariant:
    """vision.md:1019 — the second-axis key is correct ONLY because the
    bottom-up cache holds ``part1`` (NodeSummaryRaw canonical fields)
    byte-stable while ``CourseNode.content_hash`` is stable. Without
    that, LLM non-determinism would drift ``enclosing_context`` from
    re-run to re-run and child source_hashes would never match.

    Without a real LLM in scope, we close this synthetically: a stable
    ``parent.enclosing_context`` MUST produce a byte-stable source_hash
    across an arbitrary number of recomputations. This locks the
    contract that the first-axis cache is what enables the test to
    even be possible in production.
    """

    @pytest.mark.parametrize("recompute_count", [2, 5, 25])
    async def test_stable_parent_context_yields_stable_source_hash(
        self, recompute_count: int
    ) -> None:
        parent = _make_raw(enclosing_context="immutable methodist context")
        child = _make_raw()
        svc = _StubService(parent_raw=parent)
        first = await svc.compute_source_hash_for(child)
        for _ in range(recompute_count):
            assert await svc.compute_source_hash_for(child) == first
