"""Dynamic stop-word sets for natural and programming languages.

Provides stop words for natural languages and programming language
reserved words, used to filter noise during semantic identifier
matching.

The natural-language sets themselves live in
:mod:`course_supporter.linguistics`, alongside the alphabets, because the
encoding-recovery check in ``security`` needs the same words and must not
import from ``ingestion``. This module keeps the programming-language
half and the combined public API.

Supported natural languages: see
:func:`course_supporter.linguistics.supported_languages`.
Supported programming languages: Python, JavaScript, TypeScript, C#,
    Java, SQL, Rust, Go, CSS, HTML, Elixir, C, C++.
"""

from __future__ import annotations

from course_supporter.language import normalize_and_validate
from course_supporter.linguistics import NATURAL_STOP_WORDS

# ---------------------------------------------------------------------------
# Programming language reserved words
# ---------------------------------------------------------------------------

_PYTHON: frozenset[str] = frozenset(
    {
        "true",
        "false",
        "none",
        "null",
        "return",
        "import",
        "from",
        "class",
        "def",
        "self",
        "print",
        "type",
        "list",
        "dict",
        "str",
        "int",
        "float",
        "bool",
        "tuple",
        "set",
        "len",
        "pass",
        "break",
        "continue",
        "yield",
        "async",
        "await",
        "try",
        "except",
        "finally",
        "raise",
        "with",
        "as",
        "lambda",
        "global",
        "nonlocal",
        "assert",
        "del",
        "elif",
        "while",
        "range",
        "enumerate",
        "map",
        "filter",
        "super",
        "init",
        "main",
        "name",
        "args",
        "kwargs",
    }
)

_JAVASCRIPT: frozenset[str] = frozenset(
    {
        "var",
        "let",
        "const",
        "function",
        "return",
        "this",
        "new",
        "typeof",
        "instanceof",
        "delete",
        "void",
        "true",
        "false",
        "null",
        "undefined",
        "nan",
        "class",
        "extends",
        "super",
        "constructor",
        "import",
        "export",
        "default",
        "from",
        "require",
        "module",
        "async",
        "await",
        "promise",
        "then",
        "catch",
        "try",
        "finally",
        "throw",
        "console",
        "log",
        "document",
        "window",
        "array",
        "object",
        "string",
        "number",
        "boolean",
        "map",
        "filter",
        "reduce",
        "foreach",
        "push",
        "pop",
        "shift",
        "length",
        "index",
    }
)

_TYPESCRIPT: frozenset[str] = _JAVASCRIPT | frozenset(
    {
        "interface",
        "type",
        "enum",
        "readonly",
        "private",
        "public",
        "protected",
        "abstract",
        "implements",
        "declare",
        "keyof",
        "typeof",
        "infer",
        "extends",
        "never",
        "unknown",
        "any",
        "generic",
        "partial",
        "required",
        "record",
        "pick",
        "omit",
    }
)

_CSHARP: frozenset[str] = frozenset(
    {
        "var",
        "int",
        "string",
        "bool",
        "float",
        "double",
        "decimal",
        "char",
        "byte",
        "long",
        "short",
        "void",
        "object",
        "class",
        "struct",
        "enum",
        "interface",
        "abstract",
        "sealed",
        "public",
        "private",
        "protected",
        "internal",
        "static",
        "new",
        "this",
        "base",
        "return",
        "null",
        "true",
        "false",
        "try",
        "catch",
        "finally",
        "throw",
        "using",
        "namespace",
        "async",
        "await",
        "task",
        "override",
        "virtual",
        "get",
        "set",
        "value",
        "readonly",
        "const",
        "list",
        "dictionary",
        "array",
        "linq",
        "select",
        "where",
        "console",
        "writeline",
        "tostring",
    }
)

_JAVA: frozenset[str] = frozenset(
    {
        "int",
        "string",
        "boolean",
        "float",
        "double",
        "long",
        "char",
        "byte",
        "short",
        "void",
        "object",
        "class",
        "interface",
        "enum",
        "abstract",
        "final",
        "public",
        "private",
        "protected",
        "static",
        "new",
        "this",
        "super",
        "return",
        "null",
        "true",
        "false",
        "try",
        "catch",
        "finally",
        "throw",
        "throws",
        "import",
        "package",
        "extends",
        "implements",
        "override",
        "synchronized",
        "volatile",
        "transient",
        "system",
        "out",
        "println",
        "main",
        "args",
        "list",
        "map",
        "set",
        "arraylist",
        "hashmap",
        "get",
        "tostring",
        "equals",
        "hashcode",
    }
)

_SQL: frozenset[str] = frozenset(
    {
        "select",
        "from",
        "where",
        "insert",
        "update",
        "delete",
        "into",
        "values",
        "set",
        "create",
        "drop",
        "alter",
        "table",
        "column",
        "index",
        "view",
        "database",
        "schema",
        "join",
        "inner",
        "outer",
        "left",
        "right",
        "cross",
        "full",
        "group",
        "order",
        "having",
        "limit",
        "offset",
        "and",
        "not",
        "between",
        "like",
        "exists",
        "null",
        "true",
        "false",
        "default",
        "primary",
        "key",
        "foreign",
        "references",
        "constraint",
        "unique",
        "check",
        "int",
        "integer",
        "varchar",
        "text",
        "boolean",
        "date",
        "count",
        "sum",
        "avg",
        "min",
        "max",
        "distinct",
        "begin",
        "commit",
        "rollback",
        "transaction",
        "grant",
        "revoke",
        "trigger",
        "procedure",
        "function",
    }
)

_RUST: frozenset[str] = frozenset(
    {
        "let",
        "mut",
        "const",
        "static",
        "ref",
        "fn",
        "pub",
        "mod",
        "use",
        "crate",
        "super",
        "self",
        "struct",
        "enum",
        "impl",
        "trait",
        "type",
        "where",
        "return",
        "match",
        "loop",
        "while",
        "for",
        "break",
        "continue",
        "if",
        "else",
        "true",
        "false",
        "some",
        "none",
        "ok",
        "err",
        "result",
        "option",
        "vec",
        "string",
        "str",
        "box",
        "arc",
        "rc",
        "async",
        "await",
        "move",
        "clone",
        "derive",
        "println",
        "eprintln",
        "format",
        "unwrap",
        "expect",
        "usize",
        "isize",
        "bool",
        "char",
    }
)

_GO: frozenset[str] = frozenset(
    {
        "func",
        "var",
        "const",
        "type",
        "struct",
        "interface",
        "package",
        "import",
        "return",
        "defer",
        "go",
        "select",
        "chan",
        "map",
        "range",
        "make",
        "new",
        "append",
        "len",
        "cap",
        "if",
        "else",
        "for",
        "switch",
        "case",
        "default",
        "break",
        "true",
        "false",
        "nil",
        "err",
        "error",
        "int",
        "string",
        "bool",
        "float64",
        "byte",
        "rune",
        "fmt",
        "println",
        "printf",
        "sprintf",
        "goroutine",
        "channel",
        "mutex",
    }
)

_CSS: frozenset[str] = frozenset(
    {
        "display",
        "position",
        "margin",
        "padding",
        "border",
        "width",
        "height",
        "color",
        "background",
        "font",
        "flex",
        "grid",
        "block",
        "inline",
        "none",
        "auto",
        "top",
        "bottom",
        "left",
        "right",
        "center",
        "absolute",
        "relative",
        "fixed",
        "sticky",
        "hover",
        "active",
        "focus",
        "before",
        "after",
        "important",
        "inherit",
        "initial",
        "unset",
        "media",
        "keyframes",
        "animation",
        "transition",
        "var",
        "calc",
        "rgb",
        "rgba",
        "hex",
        "rem",
        "px",
        "em",
        "vh",
        "vw",
    }
)

_HTML: frozenset[str] = frozenset(
    {
        "div",
        "span",
        "class",
        "style",
        "src",
        "href",
        "alt",
        "html",
        "head",
        "body",
        "meta",
        "link",
        "script",
        "header",
        "footer",
        "main",
        "section",
        "article",
        "nav",
        "form",
        "input",
        "button",
        "select",
        "option",
        "label",
        "table",
        "thead",
        "tbody",
        "row",
        "col",
        "img",
        "video",
        "audio",
        "canvas",
        "svg",
        "onclick",
        "onchange",
        "onsubmit",
        "onload",
        "true",
        "false",
        "null",
        "undefined",
        "id",
        "name",
        "type",
        "value",
        "placeholder",
    }
)

_ELIXIR: frozenset[str] = frozenset(
    {
        "def",
        "defp",
        "defmodule",
        "defstruct",
        "defprotocol",
        "do",
        "end",
        "fn",
        "case",
        "cond",
        "with",
        "for",
        "if",
        "else",
        "unless",
        "when",
        "receive",
        "after",
        "true",
        "false",
        "nil",
        "import",
        "alias",
        "require",
        "use",
        "pipe",
        "enum",
        "map",
        "list",
        "tuple",
        "keyword",
        "spawn",
        "send",
        "self",
        "genserver",
        "supervisor",
        "ok",
        "error",
        "reply",
        "noreply",
        "stop",
        "ecto",
        "repo",
        "schema",
        "changeset",
        "migration",
        "plug",
        "conn",
        "router",
        "controller",
        "mix",
        "config",
        "application",
    }
)

_C: frozenset[str] = frozenset(
    {
        "int",
        "char",
        "float",
        "double",
        "void",
        "long",
        "short",
        "unsigned",
        "signed",
        "const",
        "static",
        "extern",
        "struct",
        "union",
        "enum",
        "typedef",
        "return",
        "if",
        "else",
        "for",
        "while",
        "do",
        "switch",
        "case",
        "break",
        "continue",
        "default",
        "goto",
        "sizeof",
        "malloc",
        "free",
        "null",
        "printf",
        "scanf",
        "fprintf",
        "sprintf",
        "include",
        "define",
        "ifdef",
        "ifndef",
        "endif",
        "main",
        "argc",
        "argv",
        "stdin",
        "stdout",
        "stderr",
    }
)

_CPP: frozenset[str] = _C | frozenset(
    {
        "class",
        "public",
        "private",
        "protected",
        "virtual",
        "new",
        "delete",
        "this",
        "template",
        "typename",
        "namespace",
        "using",
        "std",
        "cout",
        "cin",
        "endl",
        "string",
        "vector",
        "map",
        "set",
        "pair",
        "tuple",
        "auto",
        "nullptr",
        "bool",
        "true",
        "false",
        "try",
        "catch",
        "throw",
        "noexcept",
        "override",
        "final",
        "constexpr",
        "static_cast",
        "shared_ptr",
        "unique_ptr",
        "make_shared",
        "make_unique",
        "begin",
        "end",
        "push_back",
        "emplace_back",
        "size",
    }
)

_PROGRAMMING_LANGUAGES: dict[str, frozenset[str]] = {
    "python": _PYTHON,
    "javascript": _JAVASCRIPT,
    "typescript": _TYPESCRIPT,
    "csharp": _CSHARP,
    "java": _JAVA,
    "sql": _SQL,
    "rust": _RUST,
    "go": _GO,
    "css": _CSS,
    "html": _HTML,
    "elixir": _ELIXIR,
    "c": _C,
    "cpp": _CPP,
}

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_stop_words(
    *,
    natural_lang: str = "en",
    programming_lang: str = "python",
) -> frozenset[str]:
    """Build a combined stop word set for the given languages.

    Args:
        natural_lang: Any form the project accepts for a language --
            ISO 639-1, ISO 639-3, or the English name -- normalized to
            639-3 on the way in. Defaults to English.
        programming_lang: Language name (python, javascript, typescript,
            csharp, java, sql, rust, go, css, html, elixir, c, cpp).
            Defaults to Python.

    Returns:
        Combined frozenset of stop words from both sources. A whitelisted
        language that has no set yet contributes nothing, which only
        weakens the identifier filter; an unrecognized programming
        language does the same.

    Raises:
        InvalidLanguageError: ``natural_lang`` is not a language.
        LanguageNotAllowedError: it is a language, but not one the project
            allows.

    A silent empty contribution used to be the answer for both of those:
    passing ``"ukr"`` -- the very form the database stores -- returned the
    Python keywords alone and no error, so the caller got a set that
    looked usable and filtered nothing. Refusing the input is the whole
    fix; nothing else about the lookup changed.
    """
    nat = NATURAL_STOP_WORDS.get(normalize_and_validate(natural_lang), frozenset())
    prog = _PROGRAMMING_LANGUAGES.get(programming_lang, frozenset())
    return nat | prog


def supported_natural_languages() -> list[str]:
    """Return list of supported natural language codes (ISO 639-3)."""
    return list(NATURAL_STOP_WORDS.keys())


def supported_programming_languages() -> list[str]:
    """Return list of supported programming language names."""
    return list(_PROGRAMMING_LANGUAGES.keys())
