"""Dynamic stop words for cross-modal alignment.

Provides stop words for natural languages and programming language
reserved words. Used by CrossModalAligner to filter noise during
semantic identifier matching.

Supported natural languages: English, Ukrainian, German, Serbian.
Supported programming languages: Python, JavaScript, TypeScript, C#, Java, SQL.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Natural language stop words
# ---------------------------------------------------------------------------

_ENGLISH: frozenset[str] = frozenset(
    {
        "the",
        "a",
        "an",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "shall",
        "can",
        "must",
        "not",
        "no",
        "and",
        "or",
        "but",
        "if",
        "then",
        "else",
        "for",
        "in",
        "on",
        "at",
        "to",
        "from",
        "with",
        "by",
        "of",
        "that",
        "this",
        "it",
        "its",
        "we",
        "you",
        "he",
        "she",
        "they",
        "them",
        "our",
        "your",
        "my",
        "his",
        "her",
        "their",
        "what",
        "which",
        "who",
        "how",
        "when",
        "where",
        "why",
        "all",
        "each",
        "every",
        "both",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "than",
        "too",
        "very",
        "just",
        "about",
        "above",
        "after",
        "before",
        "between",
        "into",
        "through",
        "during",
        "without",
        "again",
        "further",
        "once",
        "here",
        "there",
        "so",
        "up",
        "out",
        "only",
        "also",
        "now",
        "new",
        "one",
        "two",
        "three",
        "first",
        "function",
        "method",
        "variable",
        "value",
        "used",
        "called",
        "using",
    }
)

_UKRAINIAN: frozenset[str] = frozenset(
    {
        "це",
        "та",
        "і",
        "в",
        "у",
        "на",
        "з",
        "до",
        "від",
        "за",
        "як",
        "що",
        "але",
        "або",
        "не",
        "так",
        "ми",
        "ви",
        "він",
        "вона",
        "вони",
        "воно",
        "мій",
        "наш",
        "ваш",
        "його",
        "її",
        "їх",
        "той",
        "цей",
        "ця",
        "ці",
        "тут",
        "там",
        "коли",
        "де",
        "чому",
        "який",
        "яка",
        "яке",
        "які",
        "все",
        "вже",
        "ще",
        "тільки",
        "також",
        "дуже",
        "треба",
        "можна",
        "потрібно",
        "зараз",
        "потім",
        "після",
        "перед",
        "між",
        "через",
        "без",
        "над",
        "під",
        "про",
        "функція",
        "метод",
        "змінна",
        "значення",
        "використовується",
    }
)

_GERMAN: frozenset[str] = frozenset(
    {
        "der",
        "die",
        "das",
        "ein",
        "eine",
        "ist",
        "sind",
        "war",
        "waren",
        "hat",
        "haben",
        "wird",
        "werden",
        "kann",
        "können",
        "muss",
        "müssen",
        "und",
        "oder",
        "aber",
        "wenn",
        "dann",
        "weil",
        "dass",
        "nicht",
        "mit",
        "von",
        "zu",
        "auf",
        "in",
        "an",
        "für",
        "aus",
        "bei",
        "ich",
        "du",
        "er",
        "sie",
        "es",
        "wir",
        "ihr",
        "man",
        "was",
        "wer",
        "wie",
        "wo",
        "wann",
        "warum",
        "welch",
        "hier",
        "dort",
        "jetzt",
        "noch",
        "schon",
        "auch",
        "nur",
        "sehr",
        "alle",
        "viel",
        "mehr",
        "kein",
        "jede",
        "diese",
        "neue",
        "funktion",
        "methode",
        "variable",
        "wert",
    }
)

_SERBIAN: frozenset[str] = frozenset(
    {
        "је",
        "су",
        "био",
        "била",
        "били",
        "има",
        "ће",
        "би",
        "и",
        "или",
        "али",
        "ако",
        "да",
        "не",
        "ни",
        "већ",
        "у",
        "на",
        "за",
        "од",
        "до",
        "из",
        "са",
        "по",
        "ка",
        "ја",
        "ти",
        "он",
        "она",
        "оно",
        "ми",
        "ви",
        "они",
        "мој",
        "твој",
        "наш",
        "ваш",
        "његов",
        "њен",
        "њихов",
        "тај",
        "овај",
        "онај",
        "ова",
        "ово",
        "ови",
        "шта",
        "ко",
        "како",
        "где",
        "кад",
        "зашто",
        "који",
        "све",
        "још",
        "само",
        "такође",
        "врло",
        "сада",
        "после",
        "функција",
        "метод",
        "променљива",
        "вредност",
    }
)

_NATURAL_LANGUAGES: dict[str, frozenset[str]] = {
    "en": _ENGLISH,
    "uk": _UKRAINIAN,
    "de": _GERMAN,
    "sr": _SERBIAN,
}

# ---------------------------------------------------------------------------
# Programming language reserved words
# ---------------------------------------------------------------------------

_PYTHON: frozenset[str] = frozenset(
    {
        "true",
        "false",
        "none",
        "null",
        "return",
        "import",
        "from",
        "class",
        "def",
        "self",
        "print",
        "type",
        "list",
        "dict",
        "str",
        "int",
        "float",
        "bool",
        "tuple",
        "set",
        "len",
        "pass",
        "break",
        "continue",
        "yield",
        "async",
        "await",
        "try",
        "except",
        "finally",
        "raise",
        "with",
        "as",
        "lambda",
        "global",
        "nonlocal",
        "assert",
        "del",
        "elif",
        "while",
        "range",
        "enumerate",
        "map",
        "filter",
        "super",
        "init",
        "main",
        "name",
        "args",
        "kwargs",
    }
)

_JAVASCRIPT: frozenset[str] = frozenset(
    {
        "var",
        "let",
        "const",
        "function",
        "return",
        "this",
        "new",
        "typeof",
        "instanceof",
        "delete",
        "void",
        "true",
        "false",
        "null",
        "undefined",
        "nan",
        "class",
        "extends",
        "super",
        "constructor",
        "import",
        "export",
        "default",
        "from",
        "require",
        "module",
        "async",
        "await",
        "promise",
        "then",
        "catch",
        "try",
        "finally",
        "throw",
        "console",
        "log",
        "document",
        "window",
        "array",
        "object",
        "string",
        "number",
        "boolean",
        "map",
        "filter",
        "reduce",
        "foreach",
        "push",
        "pop",
        "shift",
        "length",
        "index",
    }
)

_TYPESCRIPT: frozenset[str] = _JAVASCRIPT | frozenset(
    {
        "interface",
        "type",
        "enum",
        "readonly",
        "private",
        "public",
        "protected",
        "abstract",
        "implements",
        "declare",
        "keyof",
        "typeof",
        "infer",
        "extends",
        "never",
        "unknown",
        "any",
        "generic",
        "partial",
        "required",
        "record",
        "pick",
        "omit",
    }
)

_CSHARP: frozenset[str] = frozenset(
    {
        "var",
        "int",
        "string",
        "bool",
        "float",
        "double",
        "decimal",
        "char",
        "byte",
        "long",
        "short",
        "void",
        "object",
        "class",
        "struct",
        "enum",
        "interface",
        "abstract",
        "sealed",
        "public",
        "private",
        "protected",
        "internal",
        "static",
        "new",
        "this",
        "base",
        "return",
        "null",
        "true",
        "false",
        "try",
        "catch",
        "finally",
        "throw",
        "using",
        "namespace",
        "async",
        "await",
        "task",
        "override",
        "virtual",
        "get",
        "set",
        "value",
        "readonly",
        "const",
        "list",
        "dictionary",
        "array",
        "linq",
        "select",
        "where",
        "console",
        "writeline",
        "tostring",
    }
)

_JAVA: frozenset[str] = frozenset(
    {
        "int",
        "string",
        "boolean",
        "float",
        "double",
        "long",
        "char",
        "byte",
        "short",
        "void",
        "object",
        "class",
        "interface",
        "enum",
        "abstract",
        "final",
        "public",
        "private",
        "protected",
        "static",
        "new",
        "this",
        "super",
        "return",
        "null",
        "true",
        "false",
        "try",
        "catch",
        "finally",
        "throw",
        "throws",
        "import",
        "package",
        "extends",
        "implements",
        "override",
        "synchronized",
        "volatile",
        "transient",
        "system",
        "out",
        "println",
        "main",
        "args",
        "list",
        "map",
        "set",
        "arraylist",
        "hashmap",
        "get",
        "tostring",
        "equals",
        "hashcode",
    }
)

_SQL: frozenset[str] = frozenset(
    {
        "select",
        "from",
        "where",
        "insert",
        "update",
        "delete",
        "into",
        "values",
        "set",
        "create",
        "drop",
        "alter",
        "table",
        "column",
        "index",
        "view",
        "database",
        "schema",
        "join",
        "inner",
        "outer",
        "left",
        "right",
        "cross",
        "full",
        "group",
        "order",
        "having",
        "limit",
        "offset",
        "and",
        "not",
        "between",
        "like",
        "exists",
        "null",
        "true",
        "false",
        "default",
        "primary",
        "key",
        "foreign",
        "references",
        "constraint",
        "unique",
        "check",
        "int",
        "integer",
        "varchar",
        "text",
        "boolean",
        "date",
        "count",
        "sum",
        "avg",
        "min",
        "max",
        "distinct",
        "begin",
        "commit",
        "rollback",
        "transaction",
        "grant",
        "revoke",
        "trigger",
        "procedure",
        "function",
    }
)

_PROGRAMMING_LANGUAGES: dict[str, frozenset[str]] = {
    "python": _PYTHON,
    "javascript": _JAVASCRIPT,
    "typescript": _TYPESCRIPT,
    "csharp": _CSHARP,
    "java": _JAVA,
    "sql": _SQL,
}

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_stop_words(
    *,
    natural_lang: str = "en",
    programming_lang: str = "python",
) -> frozenset[str]:
    """Build a combined stop word set for the given languages.

    Args:
        natural_lang: ISO 639-1 code (en, uk, de, sr). Defaults to English.
        programming_lang: Language name (python, javascript, typescript,
            csharp, java, sql). Defaults to Python.

    Returns:
        Combined frozenset of stop words from both sources.
        Unknown languages are silently ignored (empty contribution).
    """
    nat = _NATURAL_LANGUAGES.get(natural_lang, frozenset())
    prog = _PROGRAMMING_LANGUAGES.get(programming_lang, frozenset())
    return nat | prog


def supported_natural_languages() -> list[str]:
    """Return list of supported natural language codes."""
    return list(_NATURAL_LANGUAGES.keys())


def supported_programming_languages() -> list[str]:
    """Return list of supported programming language names."""
    return list(_PROGRAMMING_LANGUAGES.keys())
