"""Course structure schemas."""

from datetime import UTC, datetime

from pydantic import BaseModel, Field

from course_supporter.models.source import SourceDocument


class SlideVideoMapEntry(BaseModel):
    """Pydantic mirror of ORM SlideVideoMapping.

    Maps slide_number to video_timecode (e.g., "01:23:45").
    Matches ORM: String(20) for video_timecode.
    """

    slide_number: int
    video_timecode: str


class CourseContext(BaseModel):
    """Unified context for course structuring.

    Combines all processed source documents and optional
    slide-video mappings into a single object for the
    ArchitectAgent.
    """

    documents: list[SourceDocument]
    slide_video_mappings: list[SlideVideoMapEntry] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


# --- Output models for ArchitectAgent structured output ---


class SlideRange(BaseModel):
    """Slide range for a lesson.

    Maps to ORM Lesson.slide_range (JSONB).
    Example: {"start": 1, "end": 15}
    """

    start: int
    end: int


class WebReference(BaseModel):
    """External web reference for a concept.

    Maps to ORM Concept.web_references (JSONB list).
    """

    url: str
    title: str = ""
    description: str = ""


class ExerciseOutput(BaseModel):
    """Exercise generated by ArchitectAgent.

    Suffix 'Output' to avoid collision with ORM Exercise class.
    Maps to ORM Exercise table fields.
    """

    description: str
    reference_solution: str | None = None
    grading_criteria: str | None = None
    difficulty_level: int = Field(default=3, ge=1, le=5)


class ConceptOutput(BaseModel):
    """Concept card generated by ArchitectAgent.

    Contains definition, examples, and cross-references
    to video timecodes, slides, and web resources.
    Maps to ORM Concept table fields.
    """

    title: str
    definition: str
    examples: list[str] = Field(default_factory=list)
    timecodes: list[str] = Field(default_factory=list)
    slide_references: list[int] = Field(default_factory=list)
    web_references: list[WebReference] = Field(default_factory=list)


class LessonOutput(BaseModel):
    """Lesson generated by ArchitectAgent.

    Contains concepts and exercises, plus cross-references
    to video timecodes and slide ranges.
    """

    title: str
    video_start_timecode: str | None = None
    video_end_timecode: str | None = None
    slide_range: SlideRange | None = None
    concepts: list[ConceptOutput] = Field(default_factory=list)
    exercises: list[ExerciseOutput] = Field(default_factory=list)


class ModuleOutput(BaseModel):
    """Module (section) of a course generated by ArchitectAgent."""

    title: str
    lessons: list[LessonOutput] = Field(default_factory=list)


class CourseStructure(BaseModel):
    """Top-level course structure generated by ArchitectAgent.

    This is the response_schema passed to LLM structured output.
    The LLM returns JSON conforming to this schema.
    """

    title: str
    description: str = ""
    modules: list[ModuleOutput] = Field(default_factory=list)
