"""add_jobs_table

Revision ID: 3bfcc509f45c
Revises: d3d44a540129
Create Date: 2026-02-19 21:42:53.306733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3bfcc509f45c"
down_revision: Union[str, Sequence[str], None] = "d3d44a540129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("arq_job_id", sa.String(length=100), nullable=True),
        sa.Column(
            "input_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("result_material_id", sa.Uuid(), nullable=True),
        sa.Column("result_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("depends_on", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (result_material_id IS NOT NULL AND result_snapshot_id IS NOT NULL)",
            name="chk_job_result_exclusive",
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_course_id"), "jobs", ["course_id"], unique=False)
    op.create_index(op.f("ix_jobs_node_id"), "jobs", ["node_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_node_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_course_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
