"""add learning fields to courses and modules

Revision ID: d2283f3d7212
Revises: a1b2c3d4e5f6
Create Date: 2026-02-14 18:30:08.870982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2283f3d7212"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("learning_goal", sa.Text(), nullable=True))
    op.add_column(
        "courses",
        sa.Column(
            "expected_knowledge", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "expected_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("modules", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("modules", sa.Column("learning_goal", sa.Text(), nullable=True))
    op.add_column(
        "modules",
        sa.Column(
            "expected_knowledge", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "modules",
        sa.Column(
            "expected_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "modules", sa.Column("difficulty", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modules", "difficulty")
    op.drop_column("modules", "expected_skills")
    op.drop_column("modules", "expected_knowledge")
    op.drop_column("modules", "learning_goal")
    op.drop_column("modules", "description")
    op.drop_column("courses", "expected_skills")
    op.drop_column("courses", "expected_knowledge")
    op.drop_column("courses", "learning_goal")
    # ### end Alembic commands ###
