"""make_llm_calls_tenant_id_nullable

Revision ID: d3d44a540129
Revises: ec62b2f8d538
Create Date: 2026-02-15 17:03:02.700437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3d44a540129"
down_revision: Union[str, Sequence[str], None] = "ec62b2f8d538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_calls", "tenant_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_calls", "tenant_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
