"""initial schema: 9 tables (squashed from previous migrations)

Revision ID: f7b8d706ad9c
Revises:
Create Date: 2026-03-06 10:08:27.177947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7b8d706ad9c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Multi-tenant organizations",
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "key_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the API key. Raw key is never stored",
        ),
        sa.Column(
            "key_prefix",
            sa.String(length=16),
            nullable=False,
            comment="First 8 chars of the key for identification in logs",
        ),
        sa.Column(
            "label",
            sa.String(length=100),
            nullable=False,
            server_default=sa.text("'default'"),
            comment="Human-readable label to distinguish keys in UI and logs",
        ),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="JSON array of granted scopes (prep, check)",
        ),
        sa.Column(
            "rate_limit_prep",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("60"),
            comment="Max requests per 60s window for prep scope",
        ),
        sa.Column(
            "rate_limit_check",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("300"),
            comment="Max requests per 60s window for check scope",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Authentication keys with scope-based access control",
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "material_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "parent_materialnode_id",
            sa.Uuid(),
            nullable=True,
            comment="Self-referential FK. NULL = root node (course level)",
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "learning_goal",
            sa.Text(),
            nullable=True,
            comment="Pedagogical goal text for guided generation mode",
        ),
        sa.Column(
            "expected_knowledge", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "expected_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "order",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "node_fingerprint",
            sa.String(length=64),
            nullable=True,
            comment="Merkle hash of content subtree. NULL = stale",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_materialnode_id"], ["material_nodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Hierarchical tree of course materials. Root node (parent IS NULL) = course",
    )
    op.create_index(
        op.f("ix_material_nodes_parent_materialnode_id"),
        "material_nodes",
        ["parent_materialnode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_nodes_tenant_id"),
        "material_nodes",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column(
            "materialnode_id",
            sa.Uuid(),
            nullable=True,
            comment="FK to target MaterialNode. NULL for orphaned jobs",
        ),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "priority",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'normal'"),
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'queued'"),
        ),
        sa.Column("arq_job_id", sa.String(length=100), nullable=True),
        sa.Column(
            "input_params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSONB of task-specific parameters",
        ),
        sa.Column(
            "depends_on",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSONB array of Job UUIDs that must complete first",
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["materialnode_id"], ["material_nodes.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        comment="Background task queue entries (ingestion, generation)",
    )
    op.create_index(
        op.f("ix_jobs_materialnode_id"), "jobs", ["materialnode_id"], unique=False
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    op.create_table(
        "external_service_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("prompt_ref", sa.String(length=50), nullable=True),
        sa.Column("unit_type", sa.String(length=20), nullable=True),
        sa.Column("unit_in", sa.Integer(), nullable=True),
        sa.Column("unit_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        comment="Audit log of all external API calls (LLM, transcription, etc.)",
    )
    op.create_index(
        op.f("ix_external_service_calls_job_id"),
        "external_service_calls",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_service_calls_tenant_id"),
        "external_service_calls",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "material_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "materialnode_id",
            sa.Uuid(),
            nullable=False,
            comment="FK to parent MaterialNode in the tree",
        ),
        sa.Column(
            "source_type",
            sa.Enum("video", "presentation", "text", "web", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "order",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=True),
        sa.Column(
            "raw_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 of uploaded raw file for integrity detection",
        ),
        sa.Column("raw_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "processed_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 of processed_content for Merkle tree",
        ),
        sa.Column("processed_content", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "job_id",
            sa.Uuid(),
            nullable=True,
            comment="FK to in-flight ingestion Job. NULL when idle",
        ),
        sa.Column("pending_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["materialnode_id"], ["material_nodes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Individual learning materials (video, presentation, text, web)",
    )
    op.create_index(
        op.f("ix_material_entries_job_id"), "material_entries", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_material_entries_materialnode_id"),
        "material_entries",
        ["materialnode_id"],
        unique=False,
    )
    op.create_table(
        "slide_video_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "materialnode_id",
            sa.Uuid(),
            nullable=False,
            comment="FK to owning MaterialNode",
        ),
        sa.Column("presentation_materialentry_id", sa.Uuid(), nullable=False),
        sa.Column("video_materialentry_id", sa.Uuid(), nullable=False),
        sa.Column("slide_number", sa.Integer(), nullable=False),
        sa.Column("video_timecode_start", sa.String(length=20), nullable=False),
        sa.Column("video_timecode_end", sa.String(length=20), nullable=True),
        sa.Column(
            "validation_state",
            sa.Enum(
                "validated",
                "pending_validation",
                "validation_failed",
                name="mapping_validation_state_enum",
            ),
            nullable=False,
            server_default=sa.text("'pending_validation'"),
        ),
        sa.Column(
            "blocking_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSONB array of reasons preventing validation",
        ),
        sa.Column(
            "validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["materialnode_id"], ["material_nodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["presentation_materialentry_id"],
            ["material_entries.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_materialentry_id"], ["material_entries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Presentation slide to video timecode mappings",
    )
    op.create_index(
        op.f("ix_slide_video_mappings_materialnode_id"),
        "slide_video_mappings",
        ["materialnode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slide_video_mappings_presentation_materialentry_id"),
        "slide_video_mappings",
        ["presentation_materialentry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slide_video_mappings_video_materialentry_id"),
        "slide_video_mappings",
        ["video_materialentry_id"],
        unique=False,
    )
    op.create_table(
        "structure_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "materialnode_id",
            sa.Uuid(),
            nullable=False,
            comment="FK to target MaterialNode (root = whole course)",
        ),
        sa.Column("externalservicecall_id", sa.Uuid(), nullable=True),
        sa.Column(
            "node_fingerprint",
            sa.String(length=64),
            nullable=False,
            comment="Merkle hash at generation time for idempotency",
        ),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column(
            "structure",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="JSONB of generated course structure",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["externalservicecall_id"],
            ["external_service_calls.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["materialnode_id"], ["material_nodes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="LLM-generated course structure versions",
    )
    op.create_index(
        op.f("ix_structure_snapshots_externalservicecall_id"),
        "structure_snapshots",
        ["externalservicecall_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_structure_snapshots_materialnode_id"),
        "structure_snapshots",
        ["materialnode_id"],
        unique=False,
    )
    op.create_index(
        "uq_snapshots_identity",
        "structure_snapshots",
        ["materialnode_id", "node_fingerprint", "mode"],
        unique=True,
    )
    op.create_table(
        "structure_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("structuresnapshot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "parent_structurenode_id",
            sa.Uuid(),
            nullable=True,
            comment="Self-referential FK. NULL = top-level module",
        ),
        sa.Column(
            "node_type",
            sa.String(length=30),
            nullable=False,
            comment="Enum: module, lesson, concept, exercise",
        ),
        sa.Column(
            "order",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("learning_goal", sa.Text(), nullable=True),
        sa.Column(
            "expected_knowledge", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "expected_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "prerequisites", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("estimated_duration", sa.Integer(), nullable=True),
        sa.Column("success_criteria", sa.Text(), nullable=True),
        sa.Column("assessment_method", sa.String(length=50), nullable=True),
        sa.Column(
            "competencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "key_concepts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSONB array of concept strings",
        ),
        sa.Column(
            "common_mistakes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("teaching_strategy", sa.String(length=50), nullable=True),
        sa.Column("activities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("teaching_style", sa.String(length=50), nullable=True),
        sa.Column(
            "deep_dive_references",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("content_version", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "timecodes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="JSONB of video timecode references",
        ),
        sa.Column(
            "slide_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "web_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_structurenode_id"], ["structure_nodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["structuresnapshot_id"], ["structure_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Recursive tree of generated course structure elements",
    )
    op.create_index(
        op.f("ix_structure_nodes_node_type"),
        "structure_nodes",
        ["node_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_structure_nodes_parent_structurenode_id"),
        "structure_nodes",
        ["parent_structurenode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_structure_nodes_structuresnapshot_id"),
        "structure_nodes",
        ["structuresnapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_structure_nodes_structuresnapshot_id"), table_name="structure_nodes"
    )
    op.drop_index(
        op.f("ix_structure_nodes_parent_structurenode_id"), table_name="structure_nodes"
    )
    op.drop_index(op.f("ix_structure_nodes_node_type"), table_name="structure_nodes")
    op.drop_table("structure_nodes")
    op.drop_index("uq_snapshots_identity", table_name="structure_snapshots")
    op.drop_index(
        op.f("ix_structure_snapshots_materialnode_id"), table_name="structure_snapshots"
    )
    op.drop_index(
        op.f("ix_structure_snapshots_externalservicecall_id"),
        table_name="structure_snapshots",
    )
    op.drop_table("structure_snapshots")
    op.drop_index(
        op.f("ix_slide_video_mappings_video_materialentry_id"),
        table_name="slide_video_mappings",
    )
    op.drop_index(
        op.f("ix_slide_video_mappings_presentation_materialentry_id"),
        table_name="slide_video_mappings",
    )
    op.drop_index(
        op.f("ix_slide_video_mappings_materialnode_id"),
        table_name="slide_video_mappings",
    )
    op.drop_table("slide_video_mappings")
    op.drop_index(
        op.f("ix_material_entries_materialnode_id"), table_name="material_entries"
    )
    op.drop_index(op.f("ix_material_entries_job_id"), table_name="material_entries")
    op.drop_table("material_entries")
    op.drop_index(
        op.f("ix_external_service_calls_tenant_id"), table_name="external_service_calls"
    )
    op.drop_index(
        op.f("ix_external_service_calls_job_id"), table_name="external_service_calls"
    )
    op.drop_table("external_service_calls")
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_materialnode_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_material_nodes_tenant_id"), table_name="material_nodes")
    op.drop_index(
        op.f("ix_material_nodes_parent_materialnode_id"), table_name="material_nodes"
    )
    op.drop_table("material_nodes")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("tenants")

    # Drop enum types created by sa.Enum
    op.execute("DROP TYPE IF EXISTS source_type_enum")
    op.execute("DROP TYPE IF EXISTS mapping_validation_state_enum")
    # ### end Alembic commands ###
