"""mentor-rebuild task 09b, commit K4: name the awaiting_criteria hold in the comment.

Revision ID: submission_awaiting_criteria
Revises: submission_verdict_tables
Create Date: 2026-10-02

``homework_submissions.status`` gets a second hold: ``awaiting_criteria`` — the
evaluation stage found no criteria list in force for the task, and the review
waits for one before anything is paid for (``09b-verdicts/PRE-PLAN.md``,
decision 6; ``PRE-FLIGHT.md`` 9.2в). The column is ``VARCHAR(30)`` with no
CHECK, so the state itself needs no schema change; the comment is the one place
in the database that lists the states, and it is kept whole, as
``esc_stage_money_ceiling`` kept it for ``awaiting_funds``. No back-fill: no
row can carry the new state yet.

The comment replaced was measured on the development database before writing
this file: it is the ORM's text after ``esc_stage_money_ceiling``, verbatim.

Hand-written, not autogenerated (``DD-L4-A``: autogenerate on this schema emits
~200 operations of whole-schema comment and index drift); the one operation
here is this task's.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "submission_awaiting_criteria"
down_revision: str | Sequence[str] | None = "submission_verdict_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SUBMISSIONS = "homework_submissions"

# Spelled out, not read from the ORM: a migration must not change meaning when
# the code later does.
_STATUS_COMMENT_BEFORE = (
    "Lifecycle milestone (KD15 §1298): received → safety_ok → sanity_ok → "
    "reviewing → completed → delivered; terminals rejected (safety) | "
    "mismatch (sanity) | failed (error). awaiting_funds (mentor-rebuild task "
    "03) is a hold, not a milestone: the funds port refused before the new "
    "path's first paid call, so nothing was spent; a top-up re-activates it "
    "through received."
)
_STATUS_COMMENT_AFTER = (
    _STATUS_COMMENT_BEFORE + " awaiting_criteria (task 09b) is the second hold: "
    "no criteria list is in force for the task, so the review waits for one; a "
    "continuation re-activates it through received."
)


def _set_status_comment(comment: str, existing_comment: str) -> None:
    op.alter_column(
        _SUBMISSIONS,
        "status",
        existing_type=sa.String(length=30),
        existing_nullable=False,
        comment=comment,
        existing_comment=existing_comment,
    )


def upgrade() -> None:
    """Name awaiting_criteria in the comment of the submission status."""
    _set_status_comment(_STATUS_COMMENT_AFTER, _STATUS_COMMENT_BEFORE)


def downgrade() -> None:
    """Restore the comment that names awaiting_funds only."""
    _set_status_comment(_STATUS_COMMENT_BEFORE, _STATUS_COMMENT_AFTER)
